from __future__ import annotations

from enum import StrEnum


class SerializableEnum(StrEnum):
    def to_json(self) -> str:
        return str(self.value)


class Timing(SerializableEnum):
    BATTLE_START = "BATTLE_START"
    HIT_RATE_INIT = "HIT_RATE_INIT"
    PREPARE = "PREPARE"
    ROUND_START = "ROUND_START"
    BEFORE_ACTION = "BEFORE_ACTION"
    BASIC = "BASIC"
    AFTER_BASIC = "AFTER_BASIC"
    PURSUIT = "PURSUIT"
    ACTIVE = "ACTIVE"
    AFTER_ACTION = "AFTER_ACTION"
    ROUND_END = "ROUND_END"
    BATTLE_END = "BATTLE_END"


class EventType(SerializableEnum):
    BATTLE_STARTED = "BATTLE_STARTED"
    BATTLE_FINISHED = "BATTLE_FINISHED"
    ROUND_STARTED = "ROUND_STARTED"
    ROUND_ENDED = "ROUND_ENDED"
    TIMING_STARTED = "TIMING_STARTED"
    TIMING_ENDED = "TIMING_ENDED"
    PRE_TRIGGER_CHECK = "PRE_TRIGGER_CHECK"
    TRIGGER_SUCCESS = "TRIGGER_SUCCESS"
    TRIGGER_FAIL = "TRIGGER_FAIL"
    POST_TRIGGER = "POST_TRIGGER"
    BEFORE_BASIC_SIGNAL = "BEFORE_BASIC_SIGNAL"
    BASIC_SIGNAL = "BASIC_SIGNAL"
    AFTER_BASIC_SIGNAL = "AFTER_BASIC_SIGNAL"
    BEFORE_ACTIVE_SIGNAL = "BEFORE_ACTIVE_SIGNAL"
    ACTIVE_SIGNAL = "ACTIVE_SIGNAL"
    AFTER_ACTIVE_SIGNAL = "AFTER_ACTIVE_SIGNAL"
    BEFORE_PURSUIT_SIGNAL = "BEFORE_PURSUIT_SIGNAL"
    PURSUIT_SIGNAL = "PURSUIT_SIGNAL"
    AFTER_PURSUIT_SIGNAL = "AFTER_PURSUIT_SIGNAL"
    PRE_EFFECT_CHECK = "PRE_EFFECT_CHECK"
    EFFECT_CHECK_SUCCESS = "EFFECT_CHECK_SUCCESS"
    EFFECT_CHECK_FAIL = "EFFECT_CHECK_FAIL"
    TARGET_SELECTED = "TARGET_SELECTED"
    PRE_EFFECT_EXECUTE = "PRE_EFFECT_EXECUTE"
    POST_EFFECT_EXECUTE = "POST_EFFECT_EXECUTE"
    DAMAGE_APPLIED = "DAMAGE_APPLIED"
    DAMAGE_SETTLED = "DAMAGE_SETTLED"
    HEAL_APPLIED = "HEAL_APPLIED"
    HEAL_SETTLED = "HEAL_SETTLED"
    STATE_ADDED = "STATE_ADDED"
    CONTROL_STATE_APPLIED = "CONTROL_STATE_APPLIED"
    STATE_DURATION_TICKED = "STATE_DURATION_TICKED"
    STATE_REMOVED = "STATE_REMOVED"
    ATTR_CHANGED = "ATTR_CHANGED"
    HERO_EXITED = "HERO_EXITED"
    HERO_EXITED_SETTLED = "HERO_EXITED_SETTLED"
    MAIN_HERO_EXITED = "MAIN_HERO_EXITED"
    TEAM_DEFEATED = "TEAM_DEFEATED"


class SkillCategory(SerializableEnum):
    BASIC = "BASIC"
    ACTIVE = "ACTIVE"
    PURSUIT = "PURSUIT"
    COMMAND = "COMMAND"
    PASSIVE = "PASSIVE"


class TriggerableType(SerializableEnum):
    SKILL = "SKILL"
    STATE = "STATE"


class EffectType(SerializableEnum):
    DAMAGE = "DAMAGE"
    TRUE_DAMAGE = "TRUE_DAMAGE"
    HEAL = "HEAL"
    DEBUFF = "DEBUFF"
    CONTROL_APPLY = "CONTROL_APPLY"
    DOT_APPLY = "DOT_APPLY"
    SPECIAL_STATE_GRANT = "SPECIAL_STATE_GRANT"


class DamageType(SerializableEnum):
    PHYSICAL = "PHYSICAL"
    MAGIC = "MAGIC"
    TRUE = "TRUE"


class StateType(SerializableEnum):
    ATTR = "ATTR"
    DAMAGE_REDUCE = "DAMAGE_REDUCE"
    BUFF = "BUFF"
    DEBUFF = "DEBUFF"
    CONTROL = "CONTROL"
    DOT = "DOT"
    HOT = "HOT"
    SPECIAL = "SPECIAL"


class TriggerMode(SerializableEnum):
    NONE = "NONE"
    REGULAR = "REGULAR"
    SPY = "SPY"


class TargetPolicy(SerializableEnum):
    SELF = "SELF"
    ALLY = "ALLY"
    ALLY_ALL = "ALLY_ALL"
    ALLY_LOWEST_TROOPS = "ALLY_LOWEST_TROOPS"
    ALLY_HIGHEST_TROOPS = "ALLY_HIGHEST_TROOPS"
    ENEMY = "ENEMY"
    ENEMY_ALL = "ENEMY_ALL"
    ENEMY_LOWEST_TROOPS = "ENEMY_LOWEST_TROOPS"
    ENEMY_HIGHEST_TROOPS = "ENEMY_HIGHEST_TROOPS"
    RANDOM_ENEMY = "RANDOM_ENEMY"
    RANDOM_ALLY = "RANDOM_ALLY"
    SAME_AS_PREVIOUS_EFFECT = "SAME_AS_PREVIOUS_EFFECT"
    SAME_AS_SOURCE_EVENT = "SAME_AS_SOURCE_EVENT"


class HeroRole(SerializableEnum):
    MAIN = "MAIN"
    DEPUTY = "DEPUTY"


class BattleResultType(SerializableEnum):
    TEAM_A_WIN = "TEAM_A_WIN"
    TEAM_B_WIN = "TEAM_B_WIN"
    DRAW = "DRAW"
    UNFINISHED = "UNFINISHED"
